server:
  port: 80
  servlet:
    context-path: /test
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    static-path-pattern: /pic/**

